In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
import re
import collections
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import csv
import random

Using TensorFlow backend.


In [43]:
correctSentFile = "C:\\Python364\\Scripts\\Grammar Corrector\\combined_tagged_lang_selected_entries.csv"
corrSent = pd.read_csv(correctSentFile,header=None,sep="\t")

#corrSent = corrSent[4]
corrSent = corrSent[2]
tempSent = []
print(len(corrSent))
for sent in corrSent:
    sent = sent.strip()
    sent = re.sub(r'\.{1,}',r'',sent)
    tempSent.append(sent)
'''
shuffledIndexFile = ("C:\\Python364\\Scripts\\Grammar Corrector\\shuffled-index-correct_sent.csv")
shuffledIndex = pd.read_csv(shuffledIndexFile,header=None,sep="\t")
shuffledIndex = shuffledIndex[0]
'''
bl = list(range(len(corrSent)))

random.shuffle(bl)
corrSent = []
for j in bl :
    corrSent.append(tempSent[j])
    
print(corrSent[0])
print(tempSent[0])
#corrSent[110:115]
#corrSent = ['a b c d e','a b c d e','a b c d e','a b c d e','a b c d e','a b c d e','a b c d e','a b c d e','a b c d e','a b c d e']
#print(corrSent)


99685
prp i rb vbz vbn prpd my jj nns
jj nn innn on prpd your jj nn


In [44]:
#inCorrectSentFile = "C:\\Python364\\Scripts\\Grammar Corrector\\5-combined-tagged-words-wrong-sent1.csv"
#inCorrectSentFile = "C:\\Python364\\Scripts\\Grammar Corrector\\combined-tagged-incorrect-sent2.csv"
#inCorrectSentFile = "C:\\Python364\\Scripts\\Grammar Corrector\\combined-tagged-wrong-sent-2(general errors)2.csv"
inCorrectSentFile = "C:\\Python364\\Scripts\\Grammar Corrector\\combined_tagged_specific_error_lang_selected_entries.csv"
IncorrSent = pd.read_csv(inCorrectSentFile,header=None,sep="\t")
#IncorrSent = IncorrSent[0]
IncorrSent = IncorrSent[2]
tempSent = []

for sent in IncorrSent:
    sent = sent.strip()
    sent = re.sub(r'\.{1,}',r'',sent)
    tempSent.append(sent)
    
print(len(tempSent))
    
inCorrectSentFile = "C:\\Python364\\Scripts\\Grammar Corrector\\combined_tagged_general_error_lang_selected_entries.csv"
IncorrSent = pd.read_csv(inCorrectSentFile,header=None,sep="\t")
#IncorrSent = IncorrSent[0]
IncorrSent = IncorrSent[2]

for sent in IncorrSent:
    sent = sent.strip()
    sent = re.sub(r'\.{1,}',r'',sent)
    tempSent.append(sent)
    

'''
shuffledIndexFile = ("C:\\Python364\\Scripts\\Grammar Corrector\\shuffled-index-incorrect_sent.csv")
shuffledIndex = pd.read_csv(shuffledIndexFile,header=None,sep="\t")
shuffledIndex = shuffledIndex[0] 
'''
bl = list(range(len(tempSent)))
random.shuffle(bl)

IncorrSent = []
for j in bl :
    IncorrSent.append(tempSent[j])
    
print(IncorrSent[0])
print(tempSent[0])
print(len(IncorrSent))
"""
IncorrSent = tempSent
print(len(IncorrSent))
IncorrSent[0:5]
"""
#IncorrSent = ['d e f','d e f','d e f','d e f','d e f','d e f','d e f','d e f','d e f']
#IncorrSent = ['b a c','b a c','b a c','b a c','b a c','b a c','b a c','b a c','b a c']
"""
reversed_arr = []
for i in range(len(corrSent)):
    reversed_arr.append(corrSent[i][::-1])
print(reversed_arr)
IncorrSent = reversed_arr
"""

31623
prp i vbp fouuund dt a Y jj nn innn for vbg jj nn
jj nn innn at prpd your jj nn
92082


'\nreversed_arr = []\nfor i in range(len(corrSent)):\n    reversed_arr.append(corrSent[i][::-1])\nprint(reversed_arr)\nIncorrSent = reversed_arr\n'

In [45]:
corrSent = np.array(corrSent)

zeros = np.zeros((len(corrSent),1),dtype=int) #creating labels of correct sentences
corrSent = np.reshape(corrSent,(len(corrSent),1))
corrSent = np.append(corrSent,zeros,axis=1) #
print(corrSent[2])

['nn vbz dt a V rb jj nn' '0']


In [46]:
IncorrSent = np.array(IncorrSent)
ones = np.ones((len(IncorrSent),1),dtype=int) #creating labels of incorrect sentences
IncorrSent = np.reshape(IncorrSent,(len(IncorrSent),1))
IncorrSent = np.append(IncorrSent,ones,axis=1)
print(IncorrSent[0])

['prp i vbp fouuund dt a Y jj nn innn for vbg jj nn' '1']


In [47]:
#trainSet = np.append(corrSent[0:40000,],IncorrSent[0:25000,],axis=0)
#testSet = np.append(corrSent[40000:50000,],IncorrSent[25000:30000,],axis=0)
'''
trainSet = np.append(corrSent[0:50000,],IncorrSent[0:25000,],axis=0)
trainSet = np.append(trainSet,IncorrSent[61000:86000,],axis=0)
testSet = np.append(corrSent[50000:70000,],IncorrSent[25000:30000,],axis=0)
testSet = np.append(testSet,IncorrSent[86000:91000,],axis=0)
'''

#trainSet = np.append(corrSent[0:48000,],IncorrSent[0:48000,],axis=0)
#testSet = np.append(corrSent[48000:60000,],IncorrSent[48000:60000,],axis=0)

'''
trainSet = np.append(corrSent[0:40000,],IncorrSent[0:25000,],axis=0)
trainSet = np.append(trainSet[0:65000,],IncorrSent[10000:25000,],axis=0)
testSet = np.append(corrSent[40000:50000,],IncorrSent[25000:31623,],axis=0)
testSet = np.append(testSet[0:16623,],IncorrSent[11000:14377,],axis=0)
'''


trainSet = np.append(corrSent[0:48000,],IncorrSent[0:24000,],axis=0)
trainSet = np.append(trainSet[0:72000,],IncorrSent[40000:64000,],axis=0)
testSet = np.append(corrSent[48000:60000,],IncorrSent[24000:30000,],axis=0)
testSet = np.append(testSet[0:18000,],IncorrSent[64000:70000,],axis=0)

print(trainSet[2])
#trainSet = trainSet[0:700,]
#trainSet = trainSet[0:330,]
print(len(trainSet))
print(len(testSet))

['nn vbz dt a V rb jj nn' '0']
96000
24000


In [48]:
words_counter = collections.Counter([word  for i in range(len(trainSet)) for word in trainSet[i][0].split()])
#print(words_counter)
print('{} English words.'.format(len([word  for i in range(len(trainSet)) for word in trainSet[i][0].split()])))
print('{} unique English words.'.format(len(words_counter)))
print(words_counter.most_common(10))
print(words_counter)

966695 English words.
1918 unique English words.
[('nn', 103601), ('prp', 81211), ('innn', 57643), ('dt', 55890), ('jj', 52392), ('i', 44834), ('rb', 43523), ('nnp', 37792), ('vbp', 34103), ('vb', 30123)]
Counter({'nn': 103601, 'prp': 81211, 'innn': 57643, 'dt': 55890, 'jj': 52392, 'i': 44834, 'rb': 43523, 'nnp': 37792, 'vbp': 34103, 'vb': 30123, 'vbd': 28980, 'vbz': 26901, 'nns': 24108, 'the': 17826, 'to': 17355, 'prpd': 17054, ',': 16396, 'cc': 14507, 'a': 14383, 'it': 12523, 'vbg': 12521, 'my': 12361, 'vbn': 11043, 'in': 9952, 'md': 9423, 'an': 8985, 'of': 7636, 'for': 6371, 'am': 6094, 'you': 5875, 'this': 5773, 'have': 4793, 'are': 4783, 'that': 4391, 'me': 4105, 'wrb': 3816, 'at': 3771, 'we': 3745, 'on': 3737, 'wp': 3266, 'with': 3176, 'cd': 3027, 'about': 2944, 'pos': 2783, 'L': 2533, 'like': 2521, 'he': 2518, 'ex': 2388, 'A': 2227, 'from': 2135, 'they': 2129, 'she': 2027, 'do': 1926, 'rp': 1920, 'S': 1883, 'because': 1599, 'K': 1598, 'want': 1595, 'B': 1569, 'jjr': 1560, 'some'

In [8]:
def tokenize(vocab,sentences):
    temp = {}
    for w,freq in (vocab.items()):
        if(freq > 2):
            temp[w] = freq
        
                    
    vocab = temp
    vocab_to_int = {word: ii for ii, word in enumerate(vocab, 2)} #reserving one for unknown
    vocab_to_int['unk'] = 1
    dataset_int = []
    for sent in sentences:
        #print(sent)
        sentSeq = []
        for word in sent.split():
            if word in vocab_to_int:
                sentSeq.append(vocab_to_int[word])
            else:
                sentSeq.append(vocab_to_int['unk'])
        #print(sentSeq)
        dataset_int.append(sentSeq)
    return dataset_int,vocab_to_int

text_tokenized, text_tokenizer = tokenize(words_counter,trainSet[:,0])
print(text_tokenizer)

{'dt': 2, 'the': 3, 'nn': 4, 'pos': 5, 'vbz': 6, '``': 7, 'nnp': 8, 'prp': 9, 'it': 10, 'vbd': 11, 'rb': 12, 'jj': 13, 'this': 14, 'they': 15, 'vbp': 16, 'are': 17, 'innn': 18, 'for': 19, 'me': 20, 'wrb': 21, 'to': 22, 'vb': 23, ',': 24, 'cc': 25, 'nns': 26, 'in': 27, 'ex': 28, 'a': 29, 'P': 30, 'we': 31, 'think': 32, 'prpd': 33, 'our': 34, 'my': 35, 'i': 36, 'am': 37, 'along': 38, 'W': 39, 'md': 40, 'V': 41, 'that': 42, 'have': 43, 'every': 44, 'go': 45, 'want': 46, 'an': 47, 'A': 48, 'cd': 49, 'some': 50, 'you': 51, 'she': 52, 'so': 53, 'all': 54, 'about': 55, 'vbg': 56, 'from': 57, 'D': 58, 'of': 59, 'them': 60, 'on': 61, 'with': 62, 'vbn': 63, 'K': 64, 'hope': 65, 'S': 66, 'his': 67, 'N': 68, 'like': 69, 'T': 70, 'heard': 71, 'feel': 72, 'if': 73, 'as': 74, 'belong': 75, 'because': 76, 'before': 77, 'jjs': 78, 'keep': 79, 'read': 80, 'L': 81, 'their': 82, 'he': 83, 'since': 84, 'wp': 85, 'around': 86, 'your': 87, 'her': 88, 'expect': 89, 'at': 90, 'need': 91, 'M': 92, 'wdt': 93, 'o

In [9]:
"""
def tokenize(vocab,sentences):
    vocab_to_int = {word: ii for ii, word in enumerate(vocab, 1)}
    #print(vocab)
    dataset_int = []
    for sent in sentences:
        dataset_int.append([vocab_to_int[word] for word in sent.split()])
    return dataset_int,vocab_to_int

text_tokenized, text_tokenizer = tokenize(words_counter,trainSet[:,0])
print(text_tokenizer)
"""

'\ndef tokenize(vocab,sentences):\n    vocab_to_int = {word: ii for ii, word in enumerate(vocab, 1)}\n    #print(vocab)\n    dataset_int = []\n    for sent in sentences:\n        dataset_int.append([vocab_to_int[word] for word in sent.split()])\n    return dataset_int,vocab_to_int\n\ntext_tokenized, text_tokenizer = tokenize(words_counter,trainSet[:,0])\nprint(text_tokenizer)\n'

In [10]:
def pad(x, length=None):
       
    if length is None:
        
        length = max([len(sentence) for sentence in x])
        print(length)
        
    return length,pad_sequences(x, maxlen=length, padding='post')
# Pad Tokenized output

seqLen,pad_features = pad(text_tokenized)
print(pad_features[5])
print(seqLen)


24
[ 2 14  4  6 13 26 24 26 24 25 26  0  0  0  0  0  0  0  0  0  0  0  0  0]
24


In [11]:
vocab_size = len(text_tokenizer)+1 # adding 1 for zero value added in padding
print(vocab_size)

818


In [12]:
#print(pad_features)
#seqLen = 34
def hotcodSeq(pad_features):
    
    temp2 = np.zeros((len(pad_features),seqLen,vocab_size))

    for i_seq in range((len(pad_features))):
        #print("ii "+str(i_seq))
        #print(pad_features[i_seq])
        for j_id in range(len(pad_features[i_seq])):
            if(pad_features[i_seq][j_id]==18):
                temp2[i_seq][j_id][pad_features[i_seq][j_id]] = 1
            else:
                temp2[i_seq][j_id][pad_features[i_seq][j_id]] = 1
        
        
    return temp2
    

features_x = hotcodSeq(pad_features)
print(features_x[5])

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [13]:
labels = np.array(trainSet[:,1])
labels = labels.astype(int)
print(labels[0])
print(labels.shape)

0
(96000,)


In [14]:
np.random.seed(14567)

In [18]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense,Dropout,InputLayer,Embedding
from keras.layers.core import Flatten
def lstmModel(batchSize):
    
    model = Sequential()
    batch_size = batchSize
    #model.add(Embedding(80, 10, input_length=seqLen))
    #model.add(LSTM(20,return_sequences=True,dropout=0.1,recurrent_dropout=0.1))#output dimensions batch_size,timesteps,20
    model.add(LSTM(50,batch_input_shape=(batch_size,seqLen,vocab_size),return_sequences=True,dropout=0.1,recurrent_dropout=0.1))#output dimensions batch_size,timesteps,20
    model.add(LSTM(50))
    #model.add(Flatten())
    model.add(Dense(64,activation='relu'))
    model.add(Dense(32,activation='relu'))
    model.add(Dense(8,activation='relu'))
    #model.add(Dropout(0.5))
    #model.add(Dense(1,activation='tanh'))
    #model.add(Dense(1,activation='sigmoid'))
    #model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['acc'])
    model.add(Dense(2,activation='softmax'))
    model.compile(loss='sparse_categorical_crossentropy',optimizer='rmsprop',metrics=['acc'])
    return model
model = lstmModel(4000)
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (4000, 24, 50)            173800    
_________________________________________________________________
lstm_4 (LSTM)                (4000, 50)                20200     
_________________________________________________________________
dense_5 (Dense)              (4000, 64)                3264      
_________________________________________________________________
dense_6 (Dense)              (4000, 32)                2080      
_________________________________________________________________
dense_7 (Dense)              (4000, 8)                 264       
_________________________________________________________________
dense_8 (Dense)              (4000, 2)                 18        
Total params: 199,626
Trainable params: 199,626
Non-trainable params: 0
_________________________________________________________________
None

In [ ]:
# fit the model
model.fit(features_x,labels,epochs=500,batch_size=4000,shuffle=True,verbose=1)
#embedFeatures = np.reshape(pad_features,(len(pad_features),seqLen))
#model.fit(embedFeatures,labels,epochs=50,batch_size=10,shuffle=True,verbose=1)


Epoch 1/500
52000/96000 [===============>..............] - ETA: 1:48 - loss: 0.6891 - acc: 0.5336

In [17]:
print(model.metrics_names)

model.evaluate(features_x,labels,batch_size=5000)


['loss', 'acc']
100000/100000 [==============================] - 3s 32us/step


[0.4403184786438942, 0.7725400000810623]

In [18]:
def text_2_id(tokenizer,sentences):
    dataset_int = []
    for sent in sentences:
        #print(sent)
        sentSeq = []
        for word in sent.split():
            if word in tokenizer:
                sentSeq.append(tokenizer[word])
            else:
                sentSeq.append(tokenizer['unk'])
        #print(sentSeq)
        dataset_int.append(sentSeq)
            
    #for sent in sentences:
        #dataset_int.append([vocab_to_int[w] for word in sent.split() if (word in vocab_to_int):w = word ])
    return dataset_int

testSeq = text_2_id(text_tokenizer,testSet[:,0])
seqLen,testPadSeq = pad(testSeq,seqLen)
#print(testPadSeq)
testLabels = np.array(testSet[:,1])
#print(testPadSeq)
test_features = hotcodSeq(testPadSeq)
print(testLabels.shape)

(30000,)


In [19]:
print(model.metrics_names)
#model.evaluate(test_features[0:200,],testLabels[0:200,],batch_size=100)
model.evaluate(test_features,testLabels,batch_size=5000)

['loss', 'acc']
30000/30000 [==============================] - 1s 30us/step


[0.5203609764575958, 0.746833344300588]

In [66]:
pred_model = lstmModel(1)
# copy weights
old_weights = model.get_weights()
#print(old_weights)
pred_model.set_weights=(old_weights)

In [67]:
#confusion_matrix
from sklearn.metrics import confusion_matrix
realLab = []
predLab = []
for i in range(len(trainSet)):
    testX, testy = features_x[i], trainSet[i][1]
    testX = testX.reshape(1, seqLen, vocab_size)
    #predy = pred_model.predict(testX,batch_size=1).argmax(axis=-1)[0]
    predy = pred_model.predict(testX,batch_size=1)
    print(predy)
    print(testy)
    #realLab.append(int(testy))
    #predLab.append(predy)
#print(realLab,predLab)
#print(confusion_matrix(realLab, predLab))

[[0.49446923 0.5055308 ]]
0
[[0.49446136 0.50553864]]
0
[[0.4944567 0.5055433]]
0
[[0.49444196 0.505558  ]]
0
[[0.4944567 0.5055433]]
0
[[0.49444196 0.505558  ]]
0
[[0.4944567 0.5055433]]
0
[[0.49435824 0.5056418 ]]
0
[[0.49446923 0.5055308 ]]
0
[[0.49447274 0.5055272 ]]
0
[[0.49444196 0.505558  ]]
0
[[0.49444214 0.50555784]]
0
[[0.49442554 0.50557446]]
0
[[0.49446082 0.5055391 ]]
0
[[0.49429163 0.50570834]]
0
[[0.49435434 0.50564575]]
0
[[0.49441588 0.5055842 ]]
0
[[0.49441588 0.5055842 ]]
0
[[0.49435893 0.50564104]]
0
[[0.4944567 0.5055433]]
0
[[0.49443227 0.5055677 ]]
0
[[0.49443996 0.50556   ]]
0
[[0.49442384 0.5055762 ]]
0
[[0.4944567 0.5055433]]
0
[[0.49436483 0.50563514]]
0
[[0.49433142 0.5056686 ]]
0
[[0.4944567 0.5055433]]
0
[[0.49444884 0.5055512 ]]
0
[[0.4943908 0.5056092]]
0
[[0.49444216 0.5055579 ]]
0
[[0.49445826 0.50554174]]
0
[[0.49439937 0.50560063]]
0
[[0.4945357 0.5054643]]
0
[[0.49445447 0.5055456 ]]
0
[[0.49445447 0.5055456 ]]
0
[[0.4944442  0.50555575]]
0
[[0.4944

In [127]:
from sklearn.metrics import confusion_matrix
predy = model.predict(features_x,batch_size=1).argmax(axis=-1)
labels = labels.astype(int)
print(labels)
print(confusion_matrix(labels, predy))

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1]
[[10  0]
 [ 9  0]]


In [87]:
print("hi")

hi
